### ISSUE TITLE
wis2downloader should detect HTML code != 200 and log ERROR rather than creating fake downloads

### ISSUE THREAD

**Issue by maaikelimper** [World-Meteorological-Organization/wis2downloader-v1#32]
![image](https://github.com/user-attachments/assets/2ff7944f-8d16-4f14-ba20-77127b183741)

![image](https://github.com/user-attachments/assets/39a3d0e3-b46d-4415-bce0-07a9cbd82324)

**Comment by maaikelimper** [comment]
In these lines:
https://github.com/wmo-im/wis2downloader/blob/main/wis2downloader/downloader/__init__.py#L184-L186

we should check the status before storing the data

**Comment by alimand** [comment]
Please see: https://github.com/wmo-im/wis2downloader/pull/34
