### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by david-i-berry** [World-Meteorological-Organization/wis2downloader-v1#5]
Basic auth (at a minimum) needs to be added. Currently anyone with access to the URL of the app can modify subscriptions.

**Comment by maaikelimper** [comment]
the auth does not necessarily need to be part of wis2-downloader, wis2-downloader can be used behind a proxy taking care of authenticating the auth requests

**Comment by david-i-berry** [comment]
Closing, as per comment from @maaikelimper the auth will be handled by the proxy.
