### ISSUE TITLE
Latest PR breaks downloader

### ISSUE THREAD

**Issue by david-i-berry** [World-Meteorological-Organization/wis2downloader-v1#9]
The latest PR breaks the downloader, the target validation now returns a tuple rather than cleaned sub-path, see https://github.com/wmo-im/wis2-downloader/blob/2635fed8b0ecad3fd95329d56ef112b33114b246/wis2downloader/app.py#L240.

**Comment by RoryPTB** [comment]
Addressed in PR #10.
